version: "2.0"
services:
  test:
      container_name: Integration_test
      build: .
      image: postman_report
      command:
        run Casos_de_teste.postman_collection.json
        -e environments/workspace.postman_globals.json
        -r htmlextra --reporter-htmlextra-export src/report/htmlreport.html
        
      volumes:
        - ./src:/etc/newman
