version: "2.0"
services:
  spotify_test:
      container_name: Integration_test
      build: .
      image: postman_report
      command:
        run Casos_de_teste.postman_collection.json
        -e environments/workspace.postman_globals.json
        -r html,cli
        --reporter-html-export reports/report.html
        --reporter-html-template reports/template.hbs
      volumes:
        - ./src:/etc/newman
